name: Build EMILE (bootloader)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup environment
      run: sudo apt update && sudo apt install gcc-m68k-linux-gnu meson libext2fs-dev

    - name: Setup build (bootloader)
      run: meson setup --cross-file m68k-linux-gnu.txt -Dbootloader=true build-bootloader

    - name: Build (bootloader)
      run: meson compile -C build-bootloader

    - name: Setup build (tools)
      run: meson setup --cross-file m68k-linux-gnu.txt -Dbootloader=false build-tools

    - name: Build (tools)
      run: meson compile -C build-tools
